# Generated by Django 2.0.5 on 2018-05-09 03:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCity', models.CharField(max_length=256)),
                ('UserState', models.CharField(max_length=256)),
                ('UserCountry', models.CharField(max_length=256)),
                ('UserZip', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserFirstName', models.CharField(max_length=256)),
                ('UserLastName', models.CharField(max_length=256)),
                ('UserEmail', models.EmailField(max_length=256)),
                ('UserPassword', models.CharField(max_length=256)),
                ('UserRegistrationDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('UserEmailVerified', models.IntegerField()),
                ('UserIP', models.CharField(max_length=256)),
                ('UserPhone', models.CharField(max_length=256)),
                ('UserAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Address')),
            ],
        ),
    ]
