# Generated by Django 2.0.5 on 2018-05-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserEmailVerified',
            field=models.IntegerField(default=0),
        ),
    ]
