# Generated by Django 2.0.5 on 2018-05-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180509_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserEmailVerified',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
