# Generated by Django 2.0.5 on 2018-05-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_useremailverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Address'),
        ),
    ]
