# Generated by Django 2.0.5 on 2018-05-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180509_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserFirstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserIP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserLastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserPhone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserRegistrationDate',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
