# Generated by Django 2.0.5 on 2018-05-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180509_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserEmail',
            field=models.EmailField(max_length=256),
        ),
    ]
