# Generated by Django 2.0.5 on 2018-05-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductPrice', models.IntegerField()),
                ('ProductWeight', models.FloatField()),
                ('ProductCategory', models.IntegerField()),
                ('ProductUpdateDate', models.DateField()),
                ('ProductLocation', models.IntegerField()),
                ('ProductStock', models.IntegerField()),
                ('ProductImage', models.BinaryField()),
            ],
        ),
    ]
