# Generated by Django 2.0.5 on 2018-05-11 03:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductPath',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductUpdateDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
