# Generated by Django 2.0.5 on 2018-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180511_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ProductCategoryName',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
