# Generated by Django 2.0.5 on 2018-05-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180511_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
